// drug'n'drop objects variables

var MAX_NOTES_AMOUNT = 30,
    DRAG_MODE_WIDTH = 200,
    MIN_NOTE_WIDTH = 120,
    MIN_NOTE_HEIGHT = 80,
    NOTE_DRAG_CATCH_HEIGHT = 20,
    TEXT_NOTE_DELTA_WIDTH = 25,
    TEXT_NOTE_DELTA_HEIGHT = 43;